"""add omni_interaction_id to storyboard_shots

Revision ID: 5ea025e2742e
Revises: 92ce0a22457a
Create Date: 2026-07-23 09:27:37.745123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea025e2742e'
down_revision = '92ce0a22457a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storyboard_shots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('omni_interaction_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storyboard_shots', schema=None) as batch_op:
        batch_op.drop_column('omni_interaction_id')

    # ### end Alembic commands ###
