"""initial schema

Revision ID: 765f159bd514
Revises: 
Create Date: 2026-07-20 21:05:37.512099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765f159bd514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=False),
    sa.Column('platform_style', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('material_palette', sa.String(), nullable=False),
    sa.Column('lighting', sa.String(), nullable=False),
    sa.Column('editing_style', sa.String(), nullable=False),
    sa.Column('vo_tone', sa.String(), nullable=False),
    sa.Column('music', sa.String(), nullable=False),
    sa.Column('camera_movement', sa.String(), nullable=False),
    sa.Column('words_per_second', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_table('director_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_director_prompts'))
    )
    op.create_table('menus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menus'))
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('menu_id', sa.String(), nullable=True),
    sa.Column('director_prompt_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_runs_brand_id_brands')),
    sa.ForeignKeyConstraint(['director_prompt_id'], ['director_prompts.id'], name=op.f('fk_runs_director_prompt_id_director_prompts')),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name=op.f('fk_runs_menu_id_menus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_table('media_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_media_assets_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_table('research_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_research_documents_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_documents')),
    sa.UniqueConstraint('run_id', 'version', name='uq_research_documents_run_version')
    )
    op.create_table('script_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('production', sa.JSON(), nullable=False),
    sa.Column('overview', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_script_documents_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_documents')),
    sa.UniqueConstraint('run_id', 'version', name='uq_script_documents_run_version')
    )
    op.create_table('storyboard_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('production', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_storyboard_documents_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storyboard_documents')),
    sa.UniqueConstraint('run_id', 'version', name='uq_storyboard_documents_run_version')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_usage_records_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    op.create_table('brand_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('image_asset_id', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_scenes_brand_id_brands')),
    sa.ForeignKeyConstraint(['image_asset_id'], ['media_assets.id'], name=op.f('fk_brand_scenes_image_asset_id_media_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_scenes'))
    )
    op.create_table('script_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_document_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['script_document_id'], ['script_documents.id'], name=op.f('fk_script_parts_script_document_id_script_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_parts')),
    sa.UniqueConstraint('script_document_id', 'number', name='uq_script_parts_document_number')
    )
    op.create_table('storyboard_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storyboard_document_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transition_in', sa.String(), nullable=False),
    sa.Column('music', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_document_id'], ['storyboard_documents.id'], name=op.f('fk_storyboard_scenes_storyboard_document_id_storyboard_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storyboard_scenes'))
    )
    op.create_table('subject_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('image_asset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_asset_id'], ['media_assets.id'], name=op.f('fk_subject_refs_image_asset_id_media_assets')),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name=op.f('fk_subject_refs_menu_id_menus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_refs'))
    )
    op.create_table('script_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_part_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transition', sa.String(), nullable=False),
    sa.Column('timecode_start', sa.String(), nullable=False),
    sa.Column('timecode_end', sa.String(), nullable=False),
    sa.Column('shot_type', sa.String(), nullable=False),
    sa.Column('visual_direction', sa.String(), nullable=False),
    sa.Column('voice_over', sa.String(), nullable=False),
    sa.Column('on_screen_text', sa.String(), nullable=False),
    sa.Column('key_message', sa.String(), nullable=False),
    sa.Column('music', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['script_part_id'], ['script_parts.id'], name=op.f('fk_script_scenes_script_part_id_script_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_scenes')),
    sa.UniqueConstraint('script_part_id', 'scene_id', name='uq_script_scenes_part_scene_id')
    )
    op.create_table('storyboard_shots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storyboard_scene_id', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('motion_description', sa.String(), nullable=False),
    sa.Column('voice_over', sa.String(), nullable=False),
    sa.Column('on_screen_text', sa.String(), nullable=False),
    sa.Column('key_message', sa.String(), nullable=False),
    sa.Column('shot_kind', sa.String(), nullable=False),
    sa.Column('join_with_prev', sa.String(), nullable=False),
    sa.Column('screen_direction', sa.String(), nullable=False),
    sa.Column('prompt_img', sa.String(), nullable=False),
    sa.Column('prompt_full', sa.String(), nullable=False),
    sa.Column('dish_state', sa.String(), nullable=False),
    sa.Column('prompt_video', sa.String(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('ken_burns', sa.Boolean(), nullable=False),
    sa.Column('ingredient_refs', sa.JSON(), nullable=False),
    sa.Column('equipment_refs', sa.JSON(), nullable=False),
    sa.Column('image_subjects', sa.JSON(), nullable=False),
    sa.Column('current_image_asset_id', sa.String(), nullable=True),
    sa.Column('current_video_asset_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_image_asset_id'], ['media_assets.id'], name=op.f('fk_storyboard_shots_current_image_asset_id_media_assets')),
    sa.ForeignKeyConstraint(['current_video_asset_id'], ['media_assets.id'], name=op.f('fk_storyboard_shots_current_video_asset_id_media_assets')),
    sa.ForeignKeyConstraint(['storyboard_scene_id'], ['storyboard_scenes.id'], name=op.f('fk_storyboard_shots_storyboard_scene_id_storyboard_scenes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storyboard_shots')),
    sa.UniqueConstraint('storyboard_scene_id', 'no', name='uq_storyboard_shots_scene_no')
    )
    op.create_table('shot_image_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('classified', sa.Boolean(), nullable=False),
    sa.Column('has_human', sa.Boolean(), nullable=False),
    sa.Column('has_ingredients', sa.Boolean(), nullable=False),
    sa.Column('is_process', sa.Boolean(), nullable=False),
    sa.Column('shows_dish', sa.Boolean(), nullable=False),
    sa.Column('shows_kitchen', sa.Boolean(), nullable=False),
    sa.Column('shot_scale', sa.String(), nullable=False),
    sa.Column('same_framing_as_prev', sa.Boolean(), nullable=False),
    sa.Column('scene_match', sa.String(), nullable=False),
    sa.Column('reuse_prev', sa.Boolean(), nullable=False),
    sa.Column('image_generate_type', sa.String(), nullable=False),
    sa.Column('ingredient_changed', sa.Boolean(), nullable=False),
    sa.Column('ingredient_change', sa.String(), nullable=False),
    sa.Column('equipment_changed', sa.Boolean(), nullable=False),
    sa.Column('equipment_change', sa.String(), nullable=False),
    sa.Column('process_changed', sa.Boolean(), nullable=False),
    sa.Column('process_change', sa.String(), nullable=False),
    sa.Column('ref_keywords', sa.JSON(), nullable=False),
    sa.Column('qc_passed', sa.Boolean(), nullable=False),
    sa.Column('qc_attempts', sa.Integer(), nullable=False),
    sa.Column('qc_issues', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['storyboard_shots.id'], name=op.f('fk_shot_image_plans_shot_id_storyboard_shots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_image_plans')),
    sa.UniqueConstraint('shot_id', name=op.f('uq_shot_image_plans_shot_id'))
    )
    op.create_table('shot_refs_used',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shot_image_plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['shot_image_plan_id'], ['shot_image_plans.id'], name=op.f('fk_shot_refs_used_shot_image_plan_id_shot_image_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_refs_used'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot_refs_used')
    op.drop_table('shot_image_plans')
    op.drop_table('storyboard_shots')
    op.drop_table('script_scenes')
    op.drop_table('subject_refs')
    op.drop_table('storyboard_scenes')
    op.drop_table('script_parts')
    op.drop_table('brand_scenes')
    op.drop_table('usage_records')
    op.drop_table('storyboard_documents')
    op.drop_table('script_documents')
    op.drop_table('research_documents')
    op.drop_table('media_assets')
    op.drop_table('runs')
    op.drop_table('menus')
    op.drop_table('director_prompts')
    op.drop_table('brands')
    # ### end Alembic commands ###
