"""add script_config to script_documents

Revision ID: 92ce0a22457a
Revises: 765f159bd514
Create Date: 2026-07-22 13:20:39.858447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ce0a22457a'
down_revision = '765f159bd514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script_config', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('script_documents', schema=None) as batch_op:
        batch_op.drop_column('script_config')

    # ### end Alembic commands ###
