"""add regen_events table

Revision ID: ec938dfb927d
Revises: 5ea025e2742e
Create Date: 2026-07-23 12:44:51.586227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec938dfb927d'
down_revision = '5ea025e2742e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regen_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('shot_no', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_regen_events_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regen_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regen_events')
    # ### end Alembic commands ###
